volumes:
  plex_config:
  sonarr_config:
  radarr_config:
  prowlarr_config:
  overseerr_config:
  deluge_config:

services:
  # Library explorer and content viewer
  plex:
    image: lscr.io/linuxserver/plex:latest
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - VERSION=docker
      - PLEX_CLAIM="***"
    volumes:
      - ./data/plex-config:/config
      - ./path/to/disk:/content

  # Tv show fetcher
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - sonarr_config:/config
      - ./path/to/disk:/content
    ports:
      - 8989:8989

  # Movie fetcher
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - radarr_config:/config
      - ./path/to/disk:/content
    ports:
      - 7878:7878

  # Indexer
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - prowlarr_config:/config
    ports:
      - 9696:9696

  # Request manager
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - overseerr_config:/config
    ports:
      - 5055:5055

  # VPN tunnel
  gluetun:
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN
    ports:
      - 8112:8112
      - 58946:58946
      - 58946:58946/udp
    volumes:
      - ./path/to/openvpn/config:/gluetun/openvpn
    environment:
      - TZ=Europe/Paris
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=openvpn
      - OPENVPN_CUSTOM_CONFIG=/gluetun/openvpn/config.ovpn
      - FIREWALL_OUTBOUND_SUBNETS=192.168.1.0/24

  # Torrent client
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - DELUGE_LOGLEVEL=info
    volumes:
      - deluge_config:/config
      - ./path/to/disk:/content
